WINTERSPRING = "Winterspring"
BURNING_STEPPES = "Burning Steppes"
EASTERN_PLAGUELANDS = "Eastern Plaguelands"
SILITHUS = "Silithus"
ALL = "ALL"

VALID_ZONES = { WINTERSPRING, BURNING_STEPPES, EASTERN_PLAGUELANDS, SILITHUS, ALL }

MINUTES_IN_A_DAY = 1440
MINUTES_IN_AN_HOUR = 60
SERVER_MIN_TIME_ZONE_OFFSET = -7
SERVER_MAX_TIME_ZONE_OFFSET = 17

ADDON_NAME = "LotusWindow"
ADDON_VERSION = "4.0.0"

UPDATE_PREFIX = "lw"
REQUEST_PREFIX = "lwreq"
ADDON_PREFIXES = { UPDATE_PREFIX, REQUEST_PREFIX }