WINTERSPRING = "Winterspring"
BURNING_STEPPES = "Burning Steppes"
EASTERN_PLAGUELANDS = "Eastern Plaguelands"
SILITHUS = "Silithus"
ALL = "ALL"

VALID_ZONES = { WINTERSPRING, BURNING_STEPPES, EASTERN_PLAGUELANDS, SILITHUS, ALL }

MINUTES_IN_A_DAY = 1440
MINUTES_IN_AN_HOUR = 60

ADDON_NAME = "LotusWindow"
ADDON_VERSION = "3.0.1"

MAIN_PREFIX = "lw"
REQUEST_PREFIX = "lwreq"
ADDON_PREFIXES = { MAIN_PREFIX, REQUEST_PREFIX }